# Generated by Django 2.1.7 on 2019-03-26 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(default='what', max_length=200)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=200)),
                ('ingredient_amount', models.IntegerField(default=0)),
                ('eat_date', models.DateTimeField(verbose_name='date eat')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=200)),
                ('ingredient_unit', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=200)),
                ('recipe_cal', models.IntegerField(default=0)),
                ('recipe_label', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe_ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_quantity', models.IntegerField(default=0)),
                ('ingredient_type', models.CharField(max_length=200)),
                ('ingredient_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fridge.Ingredient')),
                ('recipe_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fridge.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe_step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(default=0)),
                ('step_instructions', models.CharField(max_length=200)),
                ('recipe_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fridge.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(default='aaa', max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='user_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fridge.User'),
        ),
        migrations.AddField(
            model_name='fridge',
            name='user_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fridge.User'),
        ),
        migrations.AlterUniqueTogether(
            name='recipe_step',
            unique_together={('recipe_id', 'step_number')},
        ),
        migrations.AlterUniqueTogether(
            name='recipe_ingredient',
            unique_together={('recipe_id', 'ingredient_id')},
        ),
        migrations.AlterUniqueTogether(
            name='fridge',
            unique_together={('user_name', 'ingredient_name')},
        ),
    ]
